name: Build and Push accweb Docker Image
on:
  push:
    tags:
      - '*'
jobs:
  build-docker-accweb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |
            accweb/accweb:latest
            accweb/accweb:${{ steps.get_version.outputs.VERSION }}